package iso8583

const (
	MTI_NMM_REQUEST  = "0800"
	MTI_NMM_RESPONSE = "0810"

	// Response code constants
	RC_APPROVED             = "00"
	RC_REFER_TO_CARD_ISSUER = "01"
	RC_INVALID_MERCHANT     = "03"
	RC_DO_NOT_HONOR         = "05"
	RC_INVALID_TRANSACTION  = "12"
	RC_INVALID_AMOUNT       = "13"
	RC_INVALID_CARD_NUMBER  = "14"
	RC_FORMAT_ERROR         = "30"
	RC_SYSTEM_MALFUNCTION   = "96"
)

var DefaultConfigField = map[int]FieldConfig{
	// Field 1 is the Bitmap, handled automatically by the library

	2:  {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 19, Mandatory: false},
	3:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 6, Mandatory: true},
	4:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: true},
	5:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	6:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	7:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: true},
	8:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 8, Mandatory: false},
	9:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 8, Mandatory: false},
	10: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 8, Mandatory: false},
	11: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 6, Mandatory: true},
	12: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 6, Mandatory: true},
	13: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: true},
	14: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	15: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	16: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	17: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	18: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	19: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	20: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	21: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	22: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: true},
	23: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	24: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	25: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 2, Mandatory: true},
	26: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 2, Mandatory: false},
	27: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	28: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 9, Mandatory: false},
	29: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	30: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	31: {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 99, Mandatory: false},
	32: {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 99, Mandatory: false},
	33: {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 99, Mandatory: false},
	34: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 28, Mandatory: false},
	35: {Type: FieldTypeZ, Length: LengthLLVAR, MaxLength: 37, Mandatory: false},
	36: {Type: FieldTypeZ, Length: LengthLLVAR, MaxLength: 99, Mandatory: false},
	37: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	38: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 6, Mandatory: false},
	39: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 2, Mandatory: false},
	40: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	41: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 8, Mandatory: false},
	42: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 15, Mandatory: false},
	43: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 40, Mandatory: false},
	44: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 25, Mandatory: false},
	45: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 76, Mandatory: false},
	46: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	47: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	48: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	49: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 3, Mandatory: true},
	50: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	51: {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	52: {Type: FieldTypeB, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	53: {Type: FieldTypeN, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	54: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 120, Mandatory: false},
	55: {Type: FieldTypeB, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	56: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	57: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	58: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	59: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	60: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	61: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	62: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	63: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	64: {Type: FieldTypeB, Length: LengthFixed, MaxLength: 8, Mandatory: false},

	// --- Secondary Bitmap Fields (65-128) ---

	65:  {Type: FieldTypeB, Length: LengthFixed, MaxLength: 1, Mandatory: false},
	66:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 1, Mandatory: false},
	67:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 2, Mandatory: false},
	68:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	69:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	70:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 3, Mandatory: false},
	71:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	72:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 4, Mandatory: false},
	73:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 6, Mandatory: false},
	74:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	75:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	76:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	77:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	78:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	79:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	80:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	81:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 10, Mandatory: false},
	82:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	83:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	84:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	85:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 12, Mandatory: false},
	86:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	87:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	88:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	89:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 16, Mandatory: false},
	90:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 42, Mandatory: false},
	91:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 1, Mandatory: false},
	92:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 2, Mandatory: false},
	93:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 5, Mandatory: false},
	94:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 7, Mandatory: false},
	95:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 42, Mandatory: false},
	96:  {Type: FieldTypeB, Length: LengthFixed, MaxLength: 8, Mandatory: false},
	97:  {Type: FieldTypeN, Length: LengthFixed, MaxLength: 17, Mandatory: false},
	98:  {Type: FieldTypeANS, Length: LengthFixed, MaxLength: 25, Mandatory: false},
	99:  {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 11, Mandatory: false},
	100: {Type: FieldTypeN, Length: LengthLLVAR, MaxLength: 11, Mandatory: false},
	101: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 17, Mandatory: false},
	102: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 28, Mandatory: false},
	103: {Type: FieldTypeANS, Length: LengthLLVAR, MaxLength: 28, Mandatory: false},
	104: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 100, Mandatory: false},
	105: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	106: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	107: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	108: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	109: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	110: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	111: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	112: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	113: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	114: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	115: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	116: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	117: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	118: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	119: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	120: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	121: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	122: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	123: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	124: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	125: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	126: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	127: {Type: FieldTypeANS, Length: LengthLLLVAR, MaxLength: 999, Mandatory: false},
	128: {Type: FieldTypeB, Length: LengthFixed, MaxLength: 8, Mandatory: false},
}
